name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm i

      - name: Test
        run: npm run test